name: build

on:
  push:
    branches:
      - main

jobs:
  build_nginx_1_23:
    uses: bitcompat/base/.github/workflows/build.yaml@main
    with:
      name: main
      build-args: |
        SERVER_VERSION=1.23.0
      image_tag: |
        latest
        1.23.0-bullseye-r1 # renovate: datasource=github-releases depName=nginx/nginx
        1.23.0-bullseye # renovate: datasource=github-releases depName=nginx/nginx
        1.23.0 # renovate: datasource=github-releases depName=nginx/nginx
        1.23
        1
    secrets: inherit
  build_nginx_1_22:
    uses: bitcompat/base/.github/workflows/build.yaml@main
    with:
      name: main
      build-args: |
        SERVER_VERSION=1.22.0
      image_tag: |
        1.22.0-bullseye-r1
        1.22.0-bullseye
        1.22.0
        1.22
    secrets: inherit
